# Generated by Django 5.0.4 on 2024-04-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_created_at_room_guest_can_pause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
